module.exports = {
    TOAST: 'TOAST',
    
    SET_FILTER: 'SET_FILTER',
    SET_PATIENTS: 'SET_PATIENTS',
    ADD_PATIENT: 'ADD_PATIENT',
    UPDATE_PATIENT: 'UPDATE_PATIENT',
    REMOVE_PATIENT: 'REMOVE_PATIENT',
    SELECT_PATIENT: 'SELECT_PATIENT',
    UPDATE_SELECTED_PATIENT: 'UPDATE_SELECTED_PATIENT',
    ADD_MEDICATION: 'ADD_MEDICATION',
    UPDATE_MEDICATION: 'UPDATE_MEDICATION',
    REMOVE_MEDICATION: 'REMOVE_MEDICATION'
    
};
